linters:
  rubocop:
    display_cop_names: true
files:
  ignore:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "Gemfile.lock"
    - "test/*"
    - "node_modules/*"
    - "application_cable/channel"
    - "app/helpers/application_helper"
    - "app/helpers/"
    - "app/jobs"
    - "app/mailers"
    - "app/models/"